os: osx
language: objective-c
osx_image: xcode11.3
addons:
  homebrew:
    packages:
      - carthage
      - swiftformat
      - swiftlint
      - xcodegen
      - gpg
      - sourcery
      - blender/tap/rome
    taps:
      - blender/tap
    update: true
cache:
  directories:
    - Carthage
before_install:
  - bundle
  - rome download --platform iOS
script:
  - sh build.sh
branches:
  only:
    - master
after_success:
  - bash <(curl -s https://codecov.io/bash)
