os: osx
language: objective-c
osx_image: xcode11.3
cache:
  directories:
  - Carthage
before_install:
- brew bundle
- npm install -g apollo
- rome download --platform iOS
script:
- sh build.sh
branches:
  only:
  - master
after_success:
  - bash <(curl -s https://codecov.io/bash)